##################################################################################
#User cognito portal
cognitoEmail= automacao_coeqa@coeplard.com.br
cognitoPassword= Automacao@123
##################################################################################

##################################################################################
#Test type execution WEB or API
WEB=false
##################################################################################