##################################################################################
#Informações para execução do Testes, Geração de PDF e Testes executados no zephyr

#Nome QA responsável na hora de criar os ciclos
testerName=Bruno Silva de Souza
#Nome do domínio ou tribo
nameProject=Contratos
#ID da sua tribo
tribeProject=TRBC
userTokenZephyr=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL2YxcnN0LW9kaW4tb3JnLmF0bGFzc2lhbi5uZXQiLCJ1c2VyIjp7ImFjY291bnRJZCI6IjYzMTFmYmI3NmE4YmI0ZWRhNjc3NmQzMyJ9fSwiaXNzIjoiY29tLmthbm9haC50ZXN0LW1hbmFnZXIiLCJzdWIiOiIyYWExY2Q0My0yZGM5LTM1ZDYtYWI3Yi1iN2E0OWQ3Zjc4YmEiLCJleHAiOjE3NDM0NDQ1NjcsImlhdCI6MTcxMTkwODU2N30.yJscrUrD1B3HLFUzSTP6EJSonm9H2bDTeDrwxVRNs90
#ID da pasta onde será criado os ciclos
folderId=13508405
#Ambiente onde será executado os testes OBS: Padrão de siglas: DEV, QA LZ, UAT LZ
ambiente=QA LZ
urlZephyr=https://api.zephyrscale.smartbear.com/v2
testcycles=/testcycles
testexecutions= /testexecutions
#id do Projeto no jira
jiraProjectId=10326
#Email cadastrado no Jira
emailJira=bruno.souza@prservicos.com.br
#Token gerado do Jira
userTokenJira=ATATT3xFfGF0t4YIA4FzTlrArQ2GtgsBDtLgFGT2y4SAmNDAvbwsUvrZdAOuAsab9j7Fv-Ciwt1CmL2FMdJs1xY6Wg1w_-Nx5ySX04JsWRBXukTbR6mV3r6lURq8P2dvViJHJs98Kfwv-p55UdiY7ZArn3PsuHi46g5nJP4SXrDVlImK_USUWGk=75781F57
#id do seu perfil do Jira
userAccountId=6377eaacde5cdaba3a66bdb4
##################################################################################