##################################################################################
#Informações para execução do Testes, Geração de PDF e Testes executados no zephyr

#Nome QA responsável na hora de criar os ciclos
testerName=Bruno Cassiano
#Nome do domínio ou tribo
nameProject=Transacional
#ID da sua tribo
tribeProject=TBTR
userTokenZephyr=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL2YxcnN0LW9kaW4tb3JnLmF0bGFzc2lhbi5uZXQiLCJ1c2VyIjp7ImFjY291bnRJZCI6IjYzMTFmYmI3NmE4YmI0ZWRhNjc3NmQzMyJ9fSwiaXNzIjoiY29tLmthbm9haC50ZXN0LW1hbmFnZXIiLCJzdWIiOiIyYWExY2Q0My0yZGM5LTM1ZDYtYWI3Yi1iN2E0OWQ3Zjc4YmEiLCJleHAiOjE3NDM0NDQ1NjcsImlhdCI6MTcxMTkwODU2N30.yJscrUrD1B3HLFUzSTP6EJSonm9H2bDTeDrwxVRNs90
#ID da pasta onde será criado os ciclos
folderId=13877664
#Ambiente onde será executado os testes OBS: Padrão de siglas: DEV, QA LZ, UAT LZ
ambiente=QA LZ
urlZephyr=https://api.zephyrscale.smartbear.com/v2
testcycles=/testcycles
testexecutions= /testexecutions
#id do Projeto no jira
jiraProjectId=10400
#Email cadastrado no Jira
emailJira=kleber.almeida@prservicos.com.br
#Token gerado do Jira
userTokenJira=ATATT3xFfGF05TdlM27fOcIm7RQ6fBW6QFvVwfrH26PQjh3f_R0ug1TjE9V_r5b96n6b3cYUbvO2Cas3hiuuIs6wUcs8ZajWw95Ls67rN90So1WjW5UUNWEQ_uT0nizXSbbfEgLidt2Ix-ehugrMARWAup8mIaK-LYX9kwMYTQvUudUHIUbXmB8=BC3B8CDC
#id do seu perfil do Jira
userAccountId=632c87b88b75455be4545bca
##################################################################################